pipeline {
    agent any
    stages {
        stage('stage1') {
            steps {
                git 'https://gitlab.com/qacdevops/chaperootodo_client'
            }
        }
        stage('stage2') {
            steps {
                sudo apt-get update
                sudo apt install -y curl jq
                curl https://get.docker.com | sudo bash
                sudo usermod -aG docker $(whoami)
                //version=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')
                sudo curl -L "https://github.com/docker/compose/releases/download/${version}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose

            }
        }
        stage('stage3') {
            steps {
                sudo docker-compose pull && sudo -E DB_PASSWORD=${DB_PASSWORD} docker-compose up -d
            }
        }
    }
}