---
- hosts: all
  become: true
  tasks:
  - name: Clone Github Repo
    git:
      repo: https://github.com/cathysimms/ansible-exercise-repo.git
      dest: /home/ubuntu/repos/
      clone: yes
      update: yes 
