Resources:
  NewVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: vpc-cf

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: NewVPC

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: NewVPC
      InternetGatewayId:
        Ref: InternetGateway

  NewSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: NewVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "eu-west-1a"
      Tags:
      - Key: Name
        Value: subnet-cf

  NewSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId:
        Ref: NewVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      
  NewInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: cf-instance
      ImageId: ami-05e786af422f8082a
      InstanceType: t2.micro
      SecurityGroups:
        Ref: NewSecurityGroup
      SubnetId:
        Ref: NewSubnet
      
